name: Docker 

on: 
  workflow_call: # executado quando chamado por outro workflow

jobs: 
  docker:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3 

    # instala o docker build
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    # recuperando os artefatos
    - name: Download a Build Artefact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa # nome do artefato

    
    # login no dockerhub
    - name: Docker Login 
      uses: docker/login-action@v2.0.0 
      with: 
        username: julioszeferino
        password: ${{ secrets.PASSWD_DOCKERHUB }}

    # build e push no dockerhub
    - name: Build and Push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: . # pasta que contem os arquivos
        file: ./Dockerfile # dockerfile
        push: true
        tags: julioszeferino/go_ci:${{ github.ref_name }} # github.ref_name = branch
      
    